### ISSUE TITLE
View detail parameters of a Destination Table in the Storage to Tables Run and Conf View

### ISSUE THREAD

**Issue by romone22** [Jarvis-Platform/jarvis-studio#128]
**Is your feature request related to a problem? Please describe.**
I want to see the DDL Detail information of each Destination Table for the Run and Conf View. 
The DDL Detail information = data "encrypted" in the ddl_infos parameter in the Firestore document. 

**Describe the solution you'd like**
In the Tables table, I want a "View Details" button for each row. 
Clicking on It, a Modal Window presents 2 Tab : 
- A Schema Tab
- A Parameters Tab
The Schema Tab displays the Schema information of the table (reuse the Schema component)
The Parameters Tad displays the others parameters as the partitioning. 
For more detail,[ the Jarvis Documentation](https://app.gitbook.com/@jarvis-platform/s/home/~/drafts/-LxqDDNLvX-qT36TsO7S/j.a.r.v.i.s-configuration/storage-to-tables)

![image](https://user-images.githubusercontent.com/5988677/72133973-0a042e80-3383-11ea-901e-d6c726b52052.png)

**Additional context**
This issue demands to enrich the features of the generic "Parameters Table" component options

**Comment by Eronne** [comment]
There is a problem with `vue-good-table`, we cannot add an action column (See [this related issue](https://github.com/xaksis/vue-good-table/issues/425))

I proposed to remove this package and instead use the `v-data-table` component of `vuetify` (Doc [here](https://vuetifyjs.com/fr-FR/components/data-tables)).
