### ISSUE TITLE
Improve the Configuration Archive Action

### ISSUE THREAD

**Issue by romone22** [Jarvis-Platform/jarvis-studio#142]
**Is your feature request related to a problem? Please describe.**
The Configuration Archive Function is working well but we need to update when the archive configuration are available for which user role. 

**Describe the solution you'd like**
When a configuration is archived, it's not more visible and available for user who are not Admin or SuperAdmin. 
Moreover, for admin and super admin, the archive filter is, by default, not selected meaning the archived configuration is not loaded by default, but only activated and Disable configuration. 
The Admin or Super Admin has to ad the Archived filter in the list manually. 
For an archived configuration, the archived color is black with white text. 
For other user roles, the Archived Configuration are never loaded and the archived filter is not available.

**Additional context**
Archived configuration may not respect the configuration schema. We must be pay attention to not break the configuration listing with not well formated configuration. 
In this case, the configuration must be in the listing but with a warning message about missing or wrong mandatory parameters.

**Comment by Eronne** [comment]
Handling not well formatted configurations may be managed in an other issue as it is a general behavior.
