### ISSUE TITLE
Signin Hero Image doesn't display

### ISSUE THREAD

**Issue by romone22** [Jarvis-Platform/jarvis-studio#155]
**Describe the bug**
The Jarvis Hero Image in the SignIn page is well displayed in dev mode. But, it's no more the case when the Web App is built and serve by Firebase. 

**To Reproduce**
1. Go to https://jarvis-studio-beta.firebaseapp.com/sign-in

**Expected behavior**
See the Hero Image on the left

**Screenshots**
![image](https://user-images.githubusercontent.com/5988677/72964296-cc0efd80-3db9-11ea-8dc1-f4acb24ff3ef.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Eronne** [comment]
Issue identified => Background image path is wrong while app is builded:
- Current : `background-image: url(../img/background.fcb9a7d7.jpg);`
- Should be : `background-image: url(/img/background.fcb9a7d7.jpg);`
