### ISSUE TITLE
Add "Other Runs" Tab to a Run View

### ISSUE THREAD

**Issue by romone22** [Jarvis-Platform/jarvis-studio#161]
**Is your feature request related to a problem? Please describe.**
When analysing a Run View for a specific Run, we would like to see the other runs (past or previous) for the same Run Job Id

**Describe the solution you'd like**
Ad a "Other Runs" Tab in the Run View
![image](https://user-images.githubusercontent.com/5988677/73120834-1e474e80-3f73-11ea-930d-28e5b25f1c19.png)

In the "Other Runs" Tab, ad a listing table with all the runs for the same Job Id. 
The columns of the listing could change regarding the run configuration type, but, their the commun columns.
- Account
- Env
- Execution Date
- Dag Run Id (with link to the associated Run View)
- Status 

Some extra columns depend on the run configuration type. 
For Storage To Storage : 
- File Triggered

For Storage To Tables : 
- Triggering File

For Tables to Tables : 
no more columns

For Table to Storage : 
no more columns

For VL Launchers : 
no more columns

The current Run amoung the previous and after runs must be enlighted in bold for instance or with another color (grey) 

**Describe alternatives you've considered**
Maybe,  using a table for the listing is not the best UI approach if not enought columns.

**Comment by Eronne** [comment]
We have to add a filter to get only runs executed in the last 30 days.
We also have to provide a way to identify current run in the table.
