### ISSUE TITLE
Improve the Other Runs Tab UI

### ISSUE THREAD

**Issue by romone22** [Jarvis-Platform/jarvis-studio#174]
I'm not really convinced by the value of this feature as we implemented it. I have the feeling the features ad more complexity than simply filter the all Runs Listing with the name of the analysed Run.

Here some suggested improvements / changes for the Other Runs Tab.

- Move the "Other Runs" Tab after the Full Json Tab and before "Conversations"
- Change the Table component from GoodTable to Vuetify Table to unifie the Look and Feel with the Runs Listing
- Fore each configuration type, add the same Rows and Content as the one used for the global runs listing.
![image](https://user-images.githubusercontent.com/5988677/73515320-2c72f000-43f5-11ea-8435-20b90423d61b.png)
![image](https://user-images.githubusercontent.com/5988677/73515583-1fa2cc00-43f6-11ea-9cac-c22a168c123f.png)
By default, the Period Filter is set to 7 days and it's not the same as the global Period Filter for the Runs

_Originally posted by @romone22 in https://github.com/Jarvis-Platform/jarvis-studio/pull/168#issuecomment-580593255_

**Comment by Eronne** [comment]
This involve some changes in actual code base:
- We have to extract from current listing views (for runs) the listing component + related properties as show below to create new dedicated components:
```javascript
<listing-component
	:type="listingType"
	:module-name="moduleName"
	:headers="headers"
	:overridden-columns="overriddenColumns"
	sort-by="dag_execution_date"
	:sort-desc="true"
	show-airflow-action
>
...
</listing-component>
```
- We next have to import those new components into other-runs component
