### ISSUE TITLE
Account filter on Data Models

### ISSUE THREAD

**Issue by FelixPr** [Jarvis-Platform/jarvis-studio#184]
**Describe the bug**
We've seen during a session with Jules IT that Jules users can see the data models of other companies. They can't access the tables content but the can list data sets and table names.

**To Reproduce**
1. Create a user and associate it to Jules account
2. Go on Jarvis Studio 
3. Check the Data Models list on the upper left panel: you can see f3, gdm, orsay, and other data models. 

**Expected behavior**
A user associated with one or more accounts should only see the data models of his associated accounts.

**Additional context**
We'll soon have accounts that aren't part of Fashion3 and there's no way we can let them access Jarvis Studio if they can access other data models, and if their data model can be seen by any Fashion3 user.

**Comment by romone22** [comment]
Here the rules to filter the Data Model regarding the user : 

- Get the accounts attributed to the user profile (ex: 000050,000020)
- In the accounts collection, query the accounts attributed to the user
- For each account, extract the dlk_gcp_id_project attribut
- use this dlk_gcp_id_project attribut to filter the gbq-table-preview collectionon the id attribut (equality)

**Comment by Eronne** [comment]
Fixing this with #267
