### ISSUE TITLE
Update user avatar with drag & drop

### ISSUE THREAD

**Issue by Eronne** [Jarvis-Platform/jarvis-studio#196]
**Is your feature request related to a problem? Please describe.**
For the moment, we cannot update our `photoURL` attribute.

**Describe the solution you'd like**
Update this attribute by clicking or drag & drop an image on the `avatar-component`.

**Additional context**
Se [this tutorial](https://medium.com/javascript-in-plain-english/drag-and-drop-image-upload-with-vue-js-dropzone-and-firebase-dd6fb7e2e54b)

**Comment by Eronne** [comment]
This feature involve a change for user avatars.
In fact, for the moment, we use user `photoURL` property but we cannot update it as it is linked with user's google account.

We now have two options:
- Use separated avatars so we have to host them, they will be used only for `jarvis-studio` app
- Use user `photoURL` only but we will not be able to update them in the app

**Comment by romone22** [comment]
I suggest the feature works as explained below : 
- By default, the avatar file must be stored in the Firebase Storage. When a new user is created, if he's not logged with a social account, he must upload a picture to complete his profile. 
- if the user is only logged with a social account( including a social profile photo), we should make a copy of the avatar file in the Firebase Storage. I can replace his social avatar with another file uploaded by the user. 
- Each time a user is logged with a social account, if a never upload a personalized avatar and if his social avatar changed, we should redownload his new avatar and replace the previous one. 
- In Studia, each time we need to use the avatar, we should refer the firebase storage URL and not the social URL.

**Comment by Eronne** [comment]
Closing this issue while we are working on a new interface.
