### ISSUE TITLE
Date filter in runs listing not working on page load

### ISSUE THREAD

**Issue by Eronne** [Jarvis-Platform/jarvis-studio#206]
**Describe the bug**
When you go to. runs listing page, the date filter is not applied.

**Expected behavior**
It must be applied with "2 days" as the default value

**Comment by Eronne** [comment]
Cannot reproduce for the moment.

**Comment by Eronne** [comment]
@romone22 I just investigated on this one but cannot reproduce, I always have a filter on date even if I navigate before, if I just be logged in, etc...

Can you reproduce on your side?

**Comment by romone22** [comment]
No reproductible. Set to closed
