### ISSUE TITLE
Bug on the "Forgot Password?" feature

### ISSUE THREAD

**Issue by FelixPr** [Jarvis-Platform/jarvis-studio#242]
Matthieu Helary from Pictime (matthieu.helary@pictime-groupe.com) tried to change his password. We didn't find the feature in the Profile section so we tried the "Forgot Password?" link on the "Welcome" page. The page was refreshed, and that's it. He didn't get any email or anything. He found a warning message in the console:
![image](https://user-images.githubusercontent.com/7299985/81070619-c8743200-8ee3-11ea-904d-c3075223e532.png)

**Comment by romone22** [comment]
The method to fix this : 
- Create a new page following the password reset link with a email input form only + a Reset Password email. 
- Apply the firebase function : 
```
var auth = firebase.auth();
var emailAddress = "user@example.com";
auth.sendPasswordResetEmail(emailAddress).then(function() {
  // Email sent.
  console.log('Email Sent');
}).catch(function(error) {
  // An error happened.
});
```
- In any case, display a message explaining that "If the email exists, a reset link will be sent"

**Comment by Eronne** [comment]
This will be treated in #293
