### ISSUE TITLE
Display task status in a Table to Table Run

### ISSUE THREAD

**Issue by romone22** [Jarvis-Platform/jarvis-studio#249]
**Is your feature request related to a problem? Please describe.**
Currently, it's not possible de know which task in a TTT run is in success or failed. We have only the information at the Run Level. Being able to identify with task failed is indispensable to debug a workflow without going into Airflow. 

**Describe the solution you'd like**
In Jarvis-Studio, display, for each task in the Tasks Tab, the status of the task execution (Success, Failed or Not Executed) based of the information from a new firestore collection.

The status must be displayed with a color code as a pastille in the task cartouche in the Tasks Tab. 
![image](https://user-images.githubusercontent.com/5988677/85196320-b60a5800-b2d9-11ea-9db7-562e86e50e25.png)

Jarvis manager is know feeding a new firestore collection "gbq-to-gbq-tasks-status", storing the status of each task for a Table to Table Run instance. 

The collection stores a document for each TTT Run. The id of the document is the same as the id of the TTT Run in the gbq-to-gbq-runs collection and its the concatenation of the ID of the configuration + the Run ID of the job. It's the same used for the Jarvis Studio URL.

example: 
`https://jarvis.fashiondata.io/data-workflows/tables-to-tables/runs/000010_TTT_RFID_LOAD_BDA_RETAIL_RELOAD_FILES_DEV_scheduled__2020-06-19T06:00:00+00:00 `

Each gbq-to-gbq-tasks-status document contains a list of attributs. Each attribut corresponds to a task with a string value which could be "success" of "failed".

![image](https://user-images.githubusercontent.com/5988677/85196184-a1799000-b2d8-11ea-9226-e95a22e67f15.png)

The task which are not present as an attribut in the document correspond to not executed task.

**Describe alternatives you've considered**
We should maybe put the task list in a table in replacement of the cartouche presentation. And clicking on a line of the table will display a modal window with more information.

**Comment by Eronne** [comment]
Now on master
