### ISSUE TITLE
Wrong Update Date and Creation Date in configuration View

### ISSUE THREAD

**Issue by romone22** [Jarvis-Platform/jarvis-studio#26]
The Update Date and Create Date seem to not be well mapped.

<img width="1112" alt="Jarvis_Studio" src="https://user-images.githubusercontent.com/5988677/69708338-b9e74a80-10fb-11ea-8284-6470ee26f330.png">

**Comment by Eronne** [comment]
Can I have the URL of page(s) where it happens?

**Comment by Eronne** [comment]
@romone22 

I just fixed the `updated_date` but does it give real values before? Keys provided by the configuration object didn't have the same name in code so is this a change from the configurations and it has to be retrocompatible or is it just an error?

I also have a question for the `creation_date` field, how should we know which value to use?
When I `console.log` the configuration, I have this output:

![image](https://user-images.githubusercontent.com/10868310/69788010-df3c8d00-11bd-11ea-98ed-c3e67a109fe9.png)

**Comment by Eronne** [comment]
And other conf has:

![image](https://user-images.githubusercontent.com/10868310/69805199-7a465e80-11e0-11ea-9bbf-5f284052eb6d.png)

Which values should I be able to use for dates ?

**Comment by Eronne** [comment]
As discussed, we have two different property name for `configuration_context` : `update_date` & `updated_date`

We had to support those 2 types waiting for @julienguarino fix 🔥
