### ISSUE TITLE
Create Table to Storage Run View

### ISSUE THREAD

**Issue by romone22** [Jarvis-Platform/jarvis-studio#43]
### Detail View for a Table to Storage Run
Add a Run View for each Table to Storage Run.
4 tabs : 
1 Tab: Run informations ->  Clone the Tables to Tables model
2 Tab : Configuration informations -> As the Configuration View
3 Tab : Json Details
4 Tab : Communication

**Comment by Eronne** [comment]
On which item should I have to had the link ?
On `Destination Bucket`?

![image](https://user-images.githubusercontent.com/10868310/70349675-8035e280-1865-11ea-9254-e80f55e493fb.png)
