### ISSUE TITLE
Status Filter inefficient in Storage-to-tables view

### ISSUE THREAD

**Issue by OlivierColin** [Jarvis-Platform/jarvis-studio#85]
**Describe the bug**
When we are in the storage-to-tables view, runs tab, it seems that the status filter is unefficient.
If you choose "Failed" Status and refresh, the list shows all runs.
e.g. : https://jarvis-platform.io/data-workflows/storage-to-tables/runs

**To Reproduce**
1. Go to https://jarvis-platform.io/data-workflows/storage-to-tables/runs
2. Choose on 'FAILED' Status, "Jules" Account and refresh
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/46776827/71473808-f8deed80-27d8-11ea-98d9-e91db0ffce3a.png)

**Comment by Eronne** [comment]
This should be fixed once current PR will be merged on `master`
