### ISSUE TITLE
Account filter inefficient for workflow status

### ISSUE THREAD

**Issue by ilhamb** [Jarvis-Platform/jarvis-studio#87]
**Describe the bug**
It seems that there is an issue with the account filter in the Workflow view. 
Despite choosing a specific account, all workflows from all accounts are showing, whereas in the configuration tab, the results are filtered with the choosen account.
e.g. : https://jarvis-platform.io/data-workflows/workflow/status

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://jarvis-platform.io/data-workflows/workflow/status 
2. Click on All accounts (top left)
3. Scroll down to Grain de Malice (as an example) and refresh
4. You can see that all workflows from all accounts appear listed instead of having those related to the account.

**Screenshots**
![image](https://user-images.githubusercontent.com/8276905/71478802-b7a70780-27f1-11ea-8f9f-5ed0a6c623e5.png)

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.1
 - Browser: Chrome
 - Version: 79.0.3945.88

**Comment by Eronne** [comment]
To apply filters, we make a request on document's fields on firebase. But for workflow status, there is no `account` property on documents so we can't filter on this property.

Here is data we are now fetching:
![image.png](https://images.zenhubusercontent.com/5dd7cfc09652660001a42d37/f9d20cdb-dd38-4da1-afab-f3ca0f1a9e23)

**Comment by Eronne** [comment]
`account` field as to be available from fetched datas.
